import React from 'react';
import { Link } from 'react-router-dom';

const Home = () => {
    return (
        <div style={{ height: '100vh', padding: '20px', backgroundColor: '#212323', color: 'white' }}>
            <h1 style={{ fontSize: '48px', marginBottom: '20px' }}>Homepage</h1>
            <p style={{ fontSize: '18px', marginBottom: '30px' }}>
                This project was generated by <a href="https://www.dhiwise.com" style={{ color: '#87CEFA', textDecoration: 'none' }}>DhiWise</a>
            </p>
            <p style={{ fontSize: '18px', marginBottom: '20px' }}>
                Quickly use the links below to navigate through all pages.
            </p>
            <ul style={{ listStyle: 'none', padding: '0' }}>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        Dashboard
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/message" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        Message
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/settings" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        Settings
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/market" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        Market
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/marketdetail" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        MarketDetail
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/otheruserprofile" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        OtherUserProfile
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/activebid" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        ActiveBid
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/saved" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        Saved
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/myprofilepreview" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        MyProfilePreview
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/myprofilecollection" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        MyProfileCollection
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/myprofilewallet" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        MyProfileWallet
                    </Link>
                </li>
                <li style={{ marginBottom: '10px' }}>
                    <Link to="/myprofilehistory" style={{ color: '#87CEFA', textDecoration: 'none' }}>
                        MyProfileHistory
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;
